name: CI

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    name: test/ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - run: |
          set -o pipefail
          mvn test | tee mvn-test.log
      - if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: mvn-test-log
          path: mvn-test.log

  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
      - run: semgrep --config p/default --json --output gl-sast-report.json
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-sast-report
          path: gl-sast-report.json